### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by adamwy**

### CODE REVIEW

**Comment by densh** [comment]
Thanks for the contribution, @adamwy !

**Comment by densh** [comment]
@adamwy, please make sure that you've signed the [Scala CLA](http://www.lightbend.com/contribute/cla/scala).

**Comment by adamwy** [comment]
Hi, I did it before (and now again), please tell me if there is something wrong with my CLA submission.

**Comment by densh** [comment]
Everything is fine, just checking that all contributors sign the CLA, thanks!

**Pull request merged**
