### PR TITLE
Add a missing sentence ending in the readme

### PR DESCRIPTION
**Pull request by 2m**

### CODE REVIEW

**Comment by densh** [comment]
Please sign [Scala CLA](http://typesafe.com/contribute/cla/scala) and add yourself to the list of contributors. Thanks! :+1:

**Comment by 2m** [comment]
I have signed the CLA. Is it really good idea to keep the AUTHORS.md up to date? Instead one can just use the contributors tab in github.

**Comment by densh** [comment]
Authors file is there mostly for legal reasons. If in future a change of license or anything license-related happens it's nice to have an exhaustive list of people with their contact information. Right now I'm trying to figure out if Scala CLA has enough information for that. If it does I'll remove this file as indeed there is some extra maintenance overhead involved.

**Comment by 2m** [comment]
Roger. Added myself to the authors list.

**Comment by densh** [comment]
Thanks! :cake:

**Pull request merged**
