### PR TITLE
Adding TravisCI

### PR DESCRIPTION
**Pull request by JohnMurray**
The test are already there, this is just adding in support for TravisCI by adding a simple `.travis.yml` file and a badge to the `README.md` showing current build status.

If this is merged in @densh will have to setup TravisCI on the repo since he is the owner, which we can enable via the http://travis-ci.org webstie.

### CODE REVIEW

**Comment by JohnMurray** [comment]
Resolves #6

**Comment by densh** [comment]
LGTM, please sign [Scala CLA](https://typesafe.com/contribute/cla/scala) and add yourself to the list of contributors. Thanks! :sparkles:

**Comment by densh** [comment]
It would be also great if you could squash your commits into one.

**Comment by JohnMurray** [comment]
@densh CLA signed and commits squashed.

**Comment by densh** [comment]
Please add yourself to the list of contributors too.

**Comment by densh** [comment]
Actually there has happend minor divergence due to me adding gitter badge to README. Rebasing on top of latest master should help.

**Comment by densh** [comment]
I've merged it manually, thanks for the contribution!

**Pull request merged**
